# Configuration exemple pour IrcHumanizer
# Copiez ce fichier vers config.yaml et modifiez les valeurs

irc:
  # Serveur IRC (exemples : irc.libera.chat, irc.freenode.net)
  server: "irc.libera.chat"
  port: 6697
  ssl: true
  
  # Identité du bot
  nickname: "MonHumain"         # Si pas "MonHumain", utilise ce nom
  username: "monhumain"
  realname: "Un utilisateur normal"  # Sera remplacé par la personnalité
  
  # Automatisation de l'identité
  auto_personality_identity: true  # true = nickname/realname selon personnalité
  
  # Salons à rejoindre automatiquement
  channels:
    - "#test"
    - "#general"

behavior:
  # Probabilité de répondre à un message (0.0 = jamais, 1.0 = toujours)
  response_probability: 0.3
  
  # Délai avant réponse en secondes (pour simuler le temps de réflexion/frappe)
  min_response_delay: 1.0
  max_response_delay: 5.0

ai:
  # Clé API pour le service d'IA (utilise une variable d'environnement)
  api_key: "${OPENAI_API_KEY}"
  
  # Modèle à utiliser
  model: "gpt-3.5-turbo"

# Personnalité du bot (optionnel - si vide, génération aléatoire)
personality:
  # Identité (laisser vide pour génération aléatoire)
  name: ""           # Ex: "Alex", "Marie"  
  gender: ""         # "M", "F", ou "NB"
  age: 0             # 16-45, 0 = aléatoire
  
  # Localisation (laisser vide pour aléatoire français)
  city: ""           # Ex: "Lyon", "Paris"
  region: ""         # Ex: "69", "75" (code département)
  
  # Traits (0.0 à 1.0, vide = aléatoire)
  humor_level: 0     # Niveau d'humour
  casualness: 0      # Décontraction  
  friendliness: 0    # Amabilité
  geek_level: 0      # Côté geek
  
  # Styles d'écriture préférés (liste)
  writing_styles: []  # ["sms", "argot", "correct", "old_school"]
  
  # Centres d'intérêt personnalisés (liste)
  interests: []       # ["jeux vidéo", "musique", "sport", ...]

# Horaires d'activité et anti-détection (optionnel)
activity:
  # Timezone du bot
  timezone: "Europe/Paris"
  
  # Horaires d'activité (format HH:MM)
  active_start: "08:00"    # Début d'activité  
  active_end: "23:30"      # Fin d'activité
  
  # Pause déjeuner  
  lunch_start: "12:00"
  lunch_end: "14:00"
  lunch_probability: 0.1   # 10% de chance d'être absent
  
  # Heures de pointe (plus actif)
  peak_hours:              # Liste des créneaux
    - "19:00-22:00"
    - "09:00-10:00"
  
  # Activité weekend (0.0 à 1.0)
  weekend_activity_modifier: 0.95  # 95% de l'activité normale